/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comprobar que el proceso HTTP está vivo
         * @description Sonda de liveness sin dependencia de PostgreSQL. Una caída breve de base
         *     de datos no provoca que el runtime reinicie un proceso API saludable.
         *     Esta ruta no está sujeta al limitador global por IP y responde con
         *     `Cache-Control: no-store`.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comprobar que la API está lista para recibir tráfico
         * @description Adquiere una conexión del pool, comprueba que PostgreSQL responda y valida
         *     que las relaciones requeridas y la versión mínima del esquema estén
         *     disponibles. Esta ruta usa un timeout acotado, no está sujeta al limitador
         *     global por IP y no expone errores internos de infraestructura.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exponer métricas Prometheus del proceso
         * @description Expone métricas de HTTP, readiness, ingesta, PostgreSQL, runtime Go y
         *     build usando etiquetas de cardinalidad acotada. No incluye request IDs, item IDs,
         *     ubicaciones, tokens ni textos completos de error. Esta ruta no está sujeta
         *     al limitador global por IP.
         */
        get: operations["getPrometheusMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar el perfil y acceso efectivo del usuario autenticado
         * @description Sincroniza el usuario identificado por el claim `sub` y devuelve su plan y entitlements efectivos.
         */
        get: operations["getCurrentAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar la suscripción y los entitlements efectivos */
        get: operations["getCurrentEntitlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar estado y métricas del proceso
         * @description Devuelve uptime, salud y pool PostgreSQL, además de métricas separadas
         *     para ingesta de precios e historial. Una base no disponible conserva el
         *     mismo cuerpo y cambia el estado HTTP a `503`.
         */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar el catálogo público de mercados */
        get: operations["listMarkets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar precios actuales con parámetros simples
         * @description Ruta compatible con el contrato simple del receiver local. Para varios
         *     mercados o calidades mezcladas debe preferirse `POST /api/v1/prices/query`.
         *
         *     Las combinaciones sin datos se omiten de `data`.
         */
        get: operations["getCurrentPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar precios actuales en batch
         * @description Acepta hasta 32 mercados y 2000 pares objeto/calidad. Mercados y pares
         *     repetidos se deduplican conservando el orden lógico de la solicitud.
         *     Los campos JSON desconocidos son rechazados.
         */
        post: operations["queryCurrentPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar historial con parámetros simples
         * @description Ruta compatible con el receiver local. Puede usarse `period` o el par
         *     `rangeStart`/`rangeEnd`. Si se entrega cualquier fecha explícita, ambas
         *     son obligatorias y `period` deja de intervenir.
         *
         *     Sin rango explícito, `period` usa días UTC completados y termina en el
         *     día anterior a la fecha UTC actual. `limit` se valida por compatibilidad,
         *     pero la implementación actual no limita el número de series ni buckets.
         */
        get: operations["getMarketHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar historial en batch
         * @description Acepta hasta 32 mercados, 2000 pares objeto/calidad y un rango inclusivo
         *     máximo de 366 días. Mercados y pares repetidos se deduplican. Los campos
         *     JSON desconocidos son rechazados.
         */
        post: operations["queryMarketHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingerir precios actuales
         * @description Contrato interno idempotente. Un `request_id` nuevo responde `202`; el
         *     mismo UUID con el mismo payload ya completado responde `200`; reutilizar
         *     el UUID con otro payload o mientras sigue procesándose responde `409`.
         *
         *     El cuerpo puede enviarse sin compresión, con `Content-Encoding: identity`
         *     o con `Content-Encoding: gzip`. Todas las respuestas emitidas por el
         *     handler incluyen `Cache-Control: no-store`.
         *
         *     La implementación actual solo valida `request_id`, `server` y que
         *     `entries` no esté vacío antes del repositorio. Por eso las propiedades
         *     internas de cada entrada se describen, pero no se marcan como requeridas
         *     en este contrato de estado actual.
         */
        post: operations["ingestPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingerir historial de mercado
         * @description Contrato interno idempotente. Admite hasta 2000 capturas y hasta 100000
         *     buckets totales por request, además del límite de bytes configurado.
         *     `average_unit_price: 0` se normaliza a `null`.
         *
         *     El cuerpo puede enviarse sin compresión, con `Content-Encoding: identity`
         *     o con `Content-Encoding: gzip`. Todas las respuestas emitidas por el
         *     handler incluyen `Cache-Control: no-store`.
         */
        post: operations["ingestHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string | null;
            displayName: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            lastLoginAt: string | null;
        };
        AccountSubscription: {
            /** @enum {string} */
            plan: "free" | "pro" | "guild";
            /** @enum {string} */
            status: "none" | "trialing" | "active" | "past_due" | "canceled" | "expired";
            /** Format: date-time */
            accessUntil: string | null;
        };
        /**
         * @example {
         *       "history.max_days": 28,
         *       "optimizer.liquidity": true,
         *       "exports.csv": true
         *     }
         */
        EntitlementMap: {
            [key: string]: unknown;
        };
        AccountAccess: {
            user: components["schemas"]["AccountUser"];
            subscription: components["schemas"]["AccountSubscription"];
            entitlements: components["schemas"]["EntitlementMap"];
        };
        AccountEntitlementsResponse: {
            subscription: components["schemas"]["AccountSubscription"];
            entitlements: components["schemas"]["EntitlementMap"];
        };
        /** @enum {string} */
        Server: "west" | "east" | "europe";
        /** Format: int32 */
        Quality: number;
        /**
         * @example T4_BAG
         * @example T5_LEATHER_LEVEL4@4
         */
        ItemIdentifier: string;
        /** Format: date */
        UTCDate: string;
        /** @enum {string} */
        EnabledMarketKey: "bridgewatch" | "martlock" | "lymhurst" | "fort_sterling" | "thetford" | "caerleon" | "brecilien";
        /** @enum {string} */
        MarketKey: "bridgewatch" | "martlock" | "lymhurst" | "fort_sterling" | "thetford" | "caerleon" | "brecilien" | "black_market";
        ErrorResponse: {
            error: string;
        };
        IngestErrorResponse: {
            error: string;
            request_id?: string;
        };
        HealthOK: {
            /** @constant */
            status: "ok";
        };
        HealthUnavailable: {
            /** @constant */
            status: "error";
            /** @constant */
            error: "service unavailable";
        };
        MarketDefinition: {
            key: components["schemas"]["MarketKey"];
            name: string;
            /** @enum {string} */
            type: "regular" | "black-market";
            enabled: boolean;
        };
        MarketCatalogResponse: {
            /** @constant */
            schemaVersion: 1;
            count: number;
            data: components["schemas"]["MarketDefinition"][];
        };
        PriceQueryEntry: {
            itemIdentifier: components["schemas"]["ItemIdentifier"];
            quality: components["schemas"]["Quality"];
        };
        PriceQueryRequest: {
            server: components["schemas"]["Server"];
            marketKeys: components["schemas"]["EnabledMarketKey"][];
            entries: components["schemas"]["PriceQueryEntry"][];
        };
        CurrentPrice: {
            server: components["schemas"]["Server"];
            marketKey: components["schemas"]["EnabledMarketKey"];
            itemIdentifier: components["schemas"]["ItemIdentifier"];
            quality: components["schemas"]["Quality"];
            /** Format: int64 */
            sellPriceMin: number | null;
            /** Format: date-time */
            sellPriceMinDate: string | null;
            /** Format: int64 */
            buyPriceMax: number | null;
            /** Format: date-time */
            buyPriceMaxDate: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        PriceQueryResponse: {
            /** Format: date-time */
            requestedAt: string;
            count: number;
            data: components["schemas"]["CurrentPrice"][];
        };
        HistoryQueryEntry: {
            itemIdentifier: components["schemas"]["ItemIdentifier"];
            quality: components["schemas"]["Quality"];
        };
        HistoryQueryRequest: {
            server: components["schemas"]["Server"];
            marketKeys: components["schemas"]["EnabledMarketKey"][];
            entries: components["schemas"]["HistoryQueryEntry"][];
            rangeStart: components["schemas"]["UTCDate"];
            rangeEnd: components["schemas"]["UTCDate"];
        };
        MarketHistoryPoint: {
            /** Format: date-time */
            timestamp: string;
            /** Format: int64 */
            itemCount: number;
            /** Format: int64 */
            averageUnitPrice: number | null;
        };
        MarketHistorySeries: {
            server: components["schemas"]["Server"];
            marketKey: components["schemas"]["EnabledMarketKey"];
            itemIdentifier: components["schemas"]["ItemIdentifier"];
            quality: components["schemas"]["Quality"];
            history: components["schemas"]["MarketHistoryPoint"][];
        };
        HistoryQueryResponse: {
            /** Format: date-time */
            requestedAt: string;
            rangeStart: components["schemas"]["UTCDate"];
            rangeEnd: components["schemas"]["UTCDate"];
            count: number;
            bucketCount: number;
            data: components["schemas"]["MarketHistorySeries"][];
        };
        /**
         * @description Forma JSON actual. Ninguna propiedad se marca requerida porque la capa
         *     de servicio de precios no realiza todavía validación por entrada.
         */
        PriceIngest: {
            /** Format: date-time */
            observed_at?: string;
            /** Format: int32 */
            location_id?: number;
            item_key?: string;
            /** Format: int32 */
            quality?: number;
            /** Format: int64 */
            sell_price_min?: number | null;
            /** Format: date-time */
            sell_price_min_at?: string | null;
            /** Format: int64 */
            buy_price_max?: number | null;
            /** Format: date-time */
            buy_price_max_at?: string | null;
        };
        IngestPricesRequest: {
            /** Format: uuid */
            request_id: string;
            server: components["schemas"]["Server"];
            entries: components["schemas"]["PriceIngest"][];
        };
        IngestPricesResponseBase: {
            /** Format: uuid */
            request_id: string;
            accepted: number;
            /** Format: int64 */
            current_rows_touched: number;
            duplicate: boolean;
        };
        IngestPricesAcceptedResponse: components["schemas"]["IngestPricesResponseBase"] & {
            /** @constant */
            duplicate?: false;
        };
        IngestPricesDuplicateResponse: components["schemas"]["IngestPricesResponseBase"] & {
            /** @constant */
            duplicate?: true;
        };
        HistoryBucketIngest: {
            /** Format: date-time */
            timestamp: string;
            /** Format: int64 */
            item_count?: number;
            /**
             * Format: int64
             * @description El valor cero es aceptado y se normaliza a `null`.
             */
            average_unit_price?: number | null;
        };
        HistoryIngest: {
            /** Format: date-time */
            observed_at: string;
            /** Format: int32 */
            location_id: number;
            item_key: string;
            quality: components["schemas"]["Quality"];
            history: components["schemas"]["HistoryBucketIngest"][];
        };
        IngestHistoryRequest: {
            /** Format: uuid */
            request_id: string;
            server: components["schemas"]["Server"];
            /** @description La suma de todos los arreglos `history` no puede exceder 100000 buckets. */
            entries: components["schemas"]["HistoryIngest"][];
        };
        IngestHistoryResponseBase: {
            /** Format: uuid */
            request_id: string;
            accepted_entries: number;
            accepted_buckets: number;
            /** Format: int64 */
            history_rows_touched: number;
            duplicate: boolean;
        };
        IngestHistoryAcceptedResponse: components["schemas"]["IngestHistoryResponseBase"] & {
            /** @constant */
            duplicate?: false;
        };
        IngestHistoryDuplicateResponse: components["schemas"]["IngestHistoryResponseBase"] & {
            /** @constant */
            duplicate?: true;
        };
        StatusResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            service: string;
            environment: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            now: string;
            /** Format: int64 */
            uptime_seconds: number;
            database: components["schemas"]["DatabaseStatus"];
            ingest: components["schemas"]["IngestMetricsStatus"];
            history_ingest: components["schemas"]["HistoryIngestMetricsStatus"];
        };
        DatabaseStatus: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            ping_latency_ms: number;
            pool: components["schemas"]["DatabasePoolStatus"];
        };
        DatabasePoolStatus: {
            /** Format: int32 */
            max_connections: number;
            /** Format: int32 */
            total_connections: number;
            /** Format: int32 */
            acquired_connections: number;
            /** Format: int32 */
            idle_connections: number;
            /** Format: int32 */
            constructing_connections: number;
            /** Format: int64 */
            acquire_count: number;
            /** Format: int64 */
            empty_acquire_count: number;
            /** Format: int64 */
            canceled_acquire_count: number;
            /** Format: int64 */
            new_connections_count: number;
            acquire_duration_ms: number;
        };
        IngestMetricsStatus: {
            requests_total: number;
            in_flight: number;
            succeeded_total: number;
            duplicates_total: number;
            errors_total: number;
            accepted_entries_total: number;
            current_rows_touched_total: number;
            average_duration_ms: number;
            last_duration_ms: number;
            max_duration_ms: number;
            /** Format: date-time */
            last_request_at: string | null;
            /** Format: date-time */
            last_success_at: string | null;
            /** Format: date-time */
            last_error_at: string | null;
            last_error_kind: string;
        };
        HistoryIngestMetricsStatus: {
            requests_total: number;
            in_flight: number;
            succeeded_total: number;
            duplicates_total: number;
            errors_total: number;
            accepted_entries_total: number;
            accepted_buckets_total: number;
            history_rows_touched_total: number;
            average_duration_ms: number;
            last_duration_ms: number;
            max_duration_ms: number;
            /** Format: date-time */
            last_request_at: string | null;
            /** Format: date-time */
            last_success_at: string | null;
            /** Format: date-time */
            last_error_at: string | null;
            last_error_kind: string;
        };
    };
    responses: {
        /** @description Parámetros, JSON o reglas de negocio inválidos. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El header `Origin` no pertenece a la lista CORS permitida. */
        OriginNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "origin not allowed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Método HTTP no permitido. */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "method not allowed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Método HTTP no permitido. */
        MethodNotAllowedGet: {
            headers: {
                Allow: components["headers"]["AllowGet"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "method not allowed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Método HTTP no permitido. */
        MethodNotAllowedPost: {
            headers: {
                Allow: components["headers"]["AllowPost"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "method not allowed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El cuerpo supera el máximo público configurado. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "request body too large"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El `Content-Type` no es JSON. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "content type must be application/json"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El limitador por IP no tiene tokens disponibles. */
        RateLimited: {
            headers: {
                "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "rate limit exceeded"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Error interno sin detalles sensibles. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "internal server error"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description JSON, gzip o contrato de ingesta inválido. */
        IngestBadRequest: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["IngestErrorResponse"];
            };
        };
        /** @description Bearer token ausente, mal formado o inválido. */
        IngestUnauthorized: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                "WWW-Authenticate": components["headers"]["BearerChallenge"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["IngestErrorResponse"];
            };
        };
        /** @description Método HTTP no permitido. */
        IngestMethodNotAllowedPost: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                Allow: components["headers"]["AllowPost"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "method not allowed"
                 *     }
                 */
                "application/json": components["schemas"]["IngestErrorResponse"];
            };
        };
        /** @description Request en proceso o UUID reutilizado con otro payload. */
        IngestConflict: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["IngestErrorResponse"];
            };
        };
        /** @description El cuerpo comprimido o descomprimido supera el máximo configurado. */
        IngestPayloadTooLarge: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "request body too large"
                 *     }
                 */
                "application/json": components["schemas"]["IngestErrorResponse"];
            };
        };
        /** @description `Content-Type` o `Content-Encoding` no compatible. */
        IngestUnsupportedMediaType: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["IngestErrorResponse"];
            };
        };
        /** @description La política de ingesta exige HTTPS y la solicitud no fue reconocida como segura. */
        IngestHTTPSRequired: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                Upgrade: components["headers"]["UpgradeTLS"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "https required"
                 *     }
                 */
                "application/json": components["schemas"]["IngestErrorResponse"];
            };
        };
        /** @description Error interno sin detalles sensibles. */
        IngestInternalServerError: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "internal server error",
                 *       "request_id": "00112233-4455-6677-8899-aabbccddeeff"
                 *     }
                 */
                "application/json": components["schemas"]["IngestErrorResponse"];
            };
        };
    };
    parameters: {
        ServerQuery: components["schemas"]["Server"];
        MarketKeyQuery: components["schemas"]["EnabledMarketKey"];
        QualityQuery: components["schemas"]["Quality"];
        /** @description Codificación del cuerpo antes de aplicar el límite de bytes descomprimidos. */
        ContentEncoding: "identity" | "gzip";
    };
    requestBodies: never;
    headers: {
        /** @description Impide almacenar respuestas operacionales o de ingesta. */
        NoStore: "no-store";
        /** @description Método permitido por la ruta. */
        AllowGet: "GET";
        /** @description Método permitido por la ruta. */
        AllowPost: "POST";
        /** @description Desafío Bearer de la zona de ingesta. */
        BearerChallenge: "Bearer realm=\"ingest\"";
        /** @description Transporte requerido cuando la política HTTPS está activa. */
        UpgradeTLS: "TLS/1.2";
        /** @description Capacidad burst configurada para el cliente. */
        RateLimitLimit: number;
        /** @description Tokens restantes en el bucket del cliente. */
        RateLimitRemaining: number;
        /** @description Segundos mínimos antes de reintentar. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El proceso API está vivo. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthOK"];
                };
            };
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedGet"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API, pool PostgreSQL y esquema requeridos disponibles. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthOK"];
                };
            };
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedGet"];
            /** @description El pool, PostgreSQL o el esquema requerido no están disponibles. */
            503: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "error",
                     *       "error": "service unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthUnavailable"];
                };
            };
        };
    };
    getPrometheusMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exposición Prometheus en formato de texto 0.0.4. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # HELP albion_market_api_process_uptime_seconds API process uptime in seconds.
                     *     # TYPE albion_market_api_process_uptime_seconds gauge
                     *     albion_market_api_process_uptime_seconds 42
                     */
                    "text/plain": string;
                };
            };
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedGet"];
            /** @description El exportador no está configurado. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil, suscripción efectiva y entitlements resueltos. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountAccess"];
                };
            };
            /** @description Access token ausente, mal formado, inválido o expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedGet"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
            /** @description La autenticación de usuarios todavía no está habilitada en el runtime. */
            503: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "authentication unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentEntitlements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suscripción efectiva y mapa de entitlements del usuario. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEntitlementsResponse"];
                };
            };
            /** @description Access token ausente, mal formado, inválido o expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedGet"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
            /** @description La autenticación de usuarios todavía no está habilitada en el runtime. */
            503: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "authentication unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicio operativo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowed"];
            429: components["responses"]["RateLimited"];
            /** @description Servicio degradado porque PostgreSQL no está disponible. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    listMarkets: {
        parameters: {
            query?: {
                /** @description Incluye mercados publicados pero no habilitados para consultas. */
                includeDisabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo ordenado alfabéticamente por nombre. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "schemaVersion": 1,
                     *       "count": 7,
                     *       "data": [
                     *         {
                     *           "key": "brecilien",
                     *           "name": "Brecilien",
                     *           "type": "regular",
                     *           "enabled": true
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["MarketCatalogResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedGet"];
            429: components["responses"]["RateLimited"];
        };
    };
    getCurrentPrices: {
        parameters: {
            query: {
                server: components["parameters"]["ServerQuery"];
                marketKey: components["parameters"]["MarketKeyQuery"];
                /**
                 * @description Identificadores de objetos separados por comas.
                 * @example [
                 *       "T4_BAG",
                 *       "T5_MAIN_SWORD"
                 *     ]
                 */
                itemIds: components["schemas"]["ItemIdentifier"][];
                quality: components["parameters"]["QualityQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Precios encontrados para la matriz solicitada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceQueryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedGet"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
        };
    };
    queryCurrentPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "server": "west",
                 *       "marketKeys": [
                 *         "martlock",
                 *         "fort_sterling"
                 *       ],
                 *       "entries": [
                 *         {
                 *           "itemIdentifier": "T4_BAG",
                 *           "quality": 1
                 *         },
                 *         {
                 *           "itemIdentifier": "T5_MAIN_SWORD",
                 *           "quality": 3
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["PriceQueryRequest"];
            };
        };
        responses: {
            /** @description Precios encontrados para la matriz solicitada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceQueryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedPost"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMarketHistory: {
        parameters: {
            query: {
                server: components["parameters"]["ServerQuery"];
                marketKey: components["parameters"]["MarketKeyQuery"];
                itemId: components["schemas"]["ItemIdentifier"];
                quality: components["parameters"]["QualityQuery"];
                /** @description Periodo predefinido usado cuando no se entrega un rango explícito. */
                period?: "7-days" | "4-weeks";
                /** @description Fecha UTC inicial inclusiva; debe enviarse junto con `rangeEnd`. */
                rangeStart?: components["schemas"]["UTCDate"];
                /** @description Fecha UTC final inclusiva; debe enviarse junto con `rangeStart`. */
                rangeEnd?: components["schemas"]["UTCDate"];
                /** @description Se valida como entero positivo, pero actualmente no altera el resultado. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Series históricas encontradas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryQueryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedGet"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
        };
    };
    queryMarketHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "server": "west",
                 *       "marketKeys": [
                 *         "martlock",
                 *         "fort_sterling"
                 *       ],
                 *       "entries": [
                 *         {
                 *           "itemIdentifier": "T5_LEATHER_LEVEL4@4",
                 *           "quality": 1
                 *         }
                 *       ],
                 *       "rangeStart": "2026-06-01",
                 *       "rangeEnd": "2026-06-25"
                 *     }
                 */
                "application/json": components["schemas"]["HistoryQueryRequest"];
            };
        };
        responses: {
            /** @description Series históricas encontradas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryQueryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["MethodNotAllowedPost"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ingestPrices: {
        parameters: {
            query?: never;
            header?: {
                /** @description Codificación del cuerpo antes de aplicar el límite de bytes descomprimidos. */
                "Content-Encoding"?: components["parameters"]["ContentEncoding"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "request_id": "00112233-4455-6677-8899-aabbccddeeff",
                 *       "server": "west",
                 *       "entries": [
                 *         {
                 *           "observed_at": "2026-06-26T20:00:00Z",
                 *           "location_id": 4002,
                 *           "item_key": "T4_PLANKS_LEVEL4@4",
                 *           "quality": 1,
                 *           "sell_price_min": 1234,
                 *           "sell_price_min_at": "2026-06-26T19:59:50Z",
                 *           "buy_price_max": null,
                 *           "buy_price_max_at": null
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["IngestPricesRequest"];
            };
        };
        responses: {
            /** @description El mismo request y payload ya había sido procesado. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestPricesDuplicateResponse"];
                };
            };
            /** @description Batch nuevo aceptado y procesado. */
            202: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestPricesAcceptedResponse"];
                };
            };
            400: components["responses"]["IngestBadRequest"];
            401: components["responses"]["IngestUnauthorized"];
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["IngestMethodNotAllowedPost"];
            409: components["responses"]["IngestConflict"];
            413: components["responses"]["IngestPayloadTooLarge"];
            415: components["responses"]["IngestUnsupportedMediaType"];
            426: components["responses"]["IngestHTTPSRequired"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["IngestInternalServerError"];
        };
    };
    ingestHistory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Codificación del cuerpo antes de aplicar el límite de bytes descomprimidos. */
                "Content-Encoding"?: components["parameters"]["ContentEncoding"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "request_id": "00112233-4455-6677-8899-aabbccddeeff",
                 *       "server": "west",
                 *       "entries": [
                 *         {
                 *           "observed_at": "2026-06-26T20:00:00Z",
                 *           "location_id": 4002,
                 *           "item_key": "T5_LEATHER_LEVEL4@4",
                 *           "quality": 1,
                 *           "history": [
                 *             {
                 *               "timestamp": "2026-06-25T00:00:00Z",
                 *               "item_count": 42,
                 *               "average_unit_price": 18750
                 *             }
                 *           ]
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["IngestHistoryRequest"];
            };
        };
        responses: {
            /** @description El mismo request y payload ya había sido procesado. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestHistoryDuplicateResponse"];
                };
            };
            /** @description Batch nuevo aceptado y procesado. */
            202: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestHistoryAcceptedResponse"];
                };
            };
            400: components["responses"]["IngestBadRequest"];
            401: components["responses"]["IngestUnauthorized"];
            403: components["responses"]["OriginNotAllowed"];
            405: components["responses"]["IngestMethodNotAllowedPost"];
            409: components["responses"]["IngestConflict"];
            413: components["responses"]["IngestPayloadTooLarge"];
            415: components["responses"]["IngestUnsupportedMediaType"];
            426: components["responses"]["IngestHTTPSRequired"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["IngestInternalServerError"];
        };
    };
}
