/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMarkets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error?: string;
        };
        HealthResponse: {
            /** @constant */
            status?: "ok";
            service?: string;
        };
        ReadinessChecks: {
            /** @enum {string} */
            catalog?: "ok" | "unavailable";
            /** @enum {string} */
            repository?: "ok" | "unavailable";
        };
        ReadinessResponse: {
            /** @enum {string} */
            status?: "ready" | "not_ready";
            service?: string;
            checks?: components["schemas"]["ReadinessChecks"];
        };
        ItemDimension: {
            /** Format: int32 */
            albionId?: number;
            id?: string;
            name?: string;
        };
        LocationDimension: {
            id?: string;
            name?: string;
            marketKey?: string;
        };
        MarketDefinition: {
            key?: string;
            name?: string;
            /** @enum {string} */
            type?: "regular" | "black-market";
            cityLocationId?: string;
            marketLocationId?: string | null;
            enabled?: boolean;
        };
        QualityDimension: {
            id?: number;
            name?: string;
        };
        NormalizedHistoryPoint: {
            /** Format: date-time */
            timestamp?: string;
            /** Format: int64 */
            itemCount?: number;
            /** Format: int64 */
            totalSilver?: number;
            /** Format: double */
            averageUnitPrice?: number;
        };
        NormalizedHistorySummary: {
            /** Format: int64 */
            soldUnits?: number;
            activeBuckets?: number;
            /** Format: int64 */
            totalSilver?: number;
            /** Format: double */
            weightedAverageUnitPrice?: number;
        };
        NormalizedHistory: {
            /** @constant */
            schemaVersion?: 1;
            /** @constant */
            kind?: "market-history";
            source?: string;
            /** @enum {string} */
            server?: "west" | "east" | "europe";
            item?: components["schemas"]["ItemDimension"];
            location?: components["schemas"]["LocationDimension"];
            quality?: components["schemas"]["QualityDimension"];
            period?: string;
            /** Format: date-time */
            capturedAt?: string;
            summary?: components["schemas"]["NormalizedHistorySummary"];
            history?: components["schemas"]["NormalizedHistoryPoint"][];
            dedupeKey?: string;
        };
        NormalizedMarketOrder: {
            /** @constant */
            schemaVersion?: 1;
            /** @constant */
            kind?: "market-order";
            source?: string;
            /** @enum {string} */
            server?: "west" | "east" | "europe";
            /** Format: date-time */
            capturedAt?: string;
            /** Format: int64 */
            orderId?: number;
            item?: components["schemas"]["ItemDimension"];
            itemGroupId?: string;
            enchantmentLevel?: number;
            location?: components["schemas"]["LocationDimension"];
            quality?: components["schemas"]["QualityDimension"];
            auctionType?: string;
            /** @enum {string} */
            side?: "buy" | "sell";
            /** Format: int64 */
            unitPrice?: number;
            /** Format: int64 */
            amount?: number;
            /** Format: date-time */
            expiresAt?: string;
            dedupeKey?: string;
        };
        PriceRow: {
            server?: string;
            itemIdentifier?: string;
            marketKey?: string;
            location?: components["schemas"]["LocationDimension"];
            quality?: number;
            sellPriceMin?: number | null;
            sellPriceMinDate?: string | null;
            buyPriceMax?: number | null;
            buyPriceMaxDate?: string | null;
        };
        HistoryResponse: {
            count?: number;
            data?: components["schemas"]["NormalizedHistory"][];
            /** @constant */
            source?: "local-market-service";
        };
        OrdersResponse: {
            count?: number;
            data?: components["schemas"]["NormalizedMarketOrder"][];
            /** @constant */
            source?: "local-market-service";
        };
        PricesResponse: {
            count?: number;
            data?: components["schemas"]["PriceRow"][];
            /** @constant */
            source?: "local-market-service";
            /** Format: date-time */
            calculatedAt?: string;
        };
        MarketsResponse: {
            count?: number;
            data?: components["schemas"]["MarketDefinition"][];
            /** @constant */
            source?: "local-market-service";
        };
        RepositoryStats: {
            historySnapshots?: number;
            orderSnapshots?: number;
            /** Format: date-time */
            updatedAt?: string;
            storage?: string;
        };
        QueueSnapshot: {
            depth?: number;
            capacity?: number;
            utilization_percent?: number;
            high_watermark?: number;
        };
        OutboxPipelineSnapshot: {
            path?: string;
            pending_entries?: number;
            pending_batches?: number;
            retrying_batches?: number;
            processing_batches?: number;
            dead_letter_batches?: number;
            oldest_pending_at?: string | null;
            /** Format: int64 */
            oldest_pending_age_seconds?: number;
            recovered_batches_total?: number;
            completed_batches_total?: number;
            rescheduled_batches_total?: number;
            dead_letter_batches_total?: number;
        };
        TotalsSnapshot: {
            enqueued_entries?: number;
            queue_dropped_entries?: number;
            batches_started?: number;
            batches_sent?: number;
            entries_sent?: number;
            send_attempts?: number;
            retries?: number;
            recovered_batches?: number;
            rescheduled_batches?: number;
            failed_batches?: number;
            dead_letter_batches?: number;
            entries_dropped_after_retries?: number;
        };
        HistoryTotalsSnapshot: {
            enqueued_entries?: number;
            enqueued_buckets?: number;
            queue_dropped_entries?: number;
            queue_dropped_buckets?: number;
            batches_started?: number;
            batches_sent?: number;
            entries_sent?: number;
            buckets_sent?: number;
            send_attempts?: number;
            retries?: number;
            recovered_batches?: number;
            rescheduled_batches?: number;
            failed_batches?: number;
            dead_letter_batches?: number;
            entries_dropped_after_retries?: number;
            buckets_dropped_after_retries?: number;
        };
        LatencySnapshot: {
            last_batch_ms?: number;
            average_batch_ms?: number;
            max_batch_ms?: number;
            last_attempt_ms?: number;
        };
        ForwarderSnapshot: {
            enabled?: boolean;
            running?: boolean;
            status?: string;
            in_flight_batches?: number;
            queue?: components["schemas"]["QueueSnapshot"];
            outbox?: components["schemas"]["OutboxPipelineSnapshot"];
            totals?: components["schemas"]["TotalsSnapshot"];
            latency_ms?: components["schemas"]["LatencySnapshot"];
            last_status_code?: number;
            /** Format: date-time */
            last_success_at?: string;
            /** Format: date-time */
            last_error_at?: string;
            last_error?: string;
        };
        HistoryForwarderSnapshot: {
            enabled?: boolean;
            running?: boolean;
            status?: string;
            in_flight_batches?: number;
            queue?: components["schemas"]["QueueSnapshot"];
            outbox?: components["schemas"]["OutboxPipelineSnapshot"];
            totals?: components["schemas"]["HistoryTotalsSnapshot"];
            latency_ms?: components["schemas"]["LatencySnapshot"];
            last_status_code?: number;
            /** Format: date-time */
            last_success_at?: string;
            /** Format: date-time */
            last_error_at?: string;
            last_error?: string;
        };
        StatusResponse: {
            /** @enum {string} */
            status?: "ok" | "degraded";
            service?: string;
            environment?: string;
            /** @constant */
            source?: "local-market-service";
            /** Format: int64 */
            uptime_seconds?: number;
            repository?: components["schemas"]["RepositoryStats"];
            forwarder?: components["schemas"]["ForwarderSnapshot"];
            price_forwarder?: components["schemas"]["ForwarderSnapshot"];
            history_forwarder?: components["schemas"]["HistoryForwarderSnapshot"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Response. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    listMarkets: {
        parameters: {
            query?: {
                includeDisabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketsResponse"];
                };
            };
        };
    };
    getPrices: {
        parameters: {
            query: {
                server?: "west" | "east" | "europe";
                itemIds?: string;
                itemId?: string;
                marketKey?: string;
                locationId?: string;
                location?: string;
                quality: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
        };
    };
    listHistory: {
        parameters: {
            query?: {
                server?: "west" | "east" | "europe";
                itemId?: string;
                marketKey?: string;
                locationId?: string;
                location?: string;
                quality?: number;
                period?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: {
                server?: "west" | "east" | "europe";
                itemId?: string;
                marketKey?: string;
                locationId?: string;
                location?: string;
                quality?: number;
                auctionType?: string;
                side?: "buy" | "sell";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersResponse"];
                };
            };
        };
    };
}
